### ISSUE TITLE
`KeyError: 'likeCount'`

### ISSUE THREAD

**Issue by bitterteriyaki** [vmussa/qualitube#2]
I am creating an issue here because I cannot create it on [LABHDUFBA repository](https://github.com/LABHDUFBA/qualitube).

I am using `Videos.to_df()` manually and I am getting this following error:
```py
  File "/home/.../qualichat/frames.py", line 395, in rating
    dataframes: List[DataFrame] = [v.to_df() for v in data]
  File "/home/.../qualichat/frames.py", line 395, in <listcomp>
    dataframes: List[DataFrame] = [v.to_df() for v in data]
  File "/home/.../qualitube/videos.py", line 92, in to_df
    df = pd.DataFrame(self.get_data())
  File "/home/.../qualitube/videos.py", line 84, in get_data
    videos_data, next_page_token = self._parse_response(r.text)
  File "/home/.../qualitube/videos.py", line 47, in _parse_response
    'video_like_count': item['statistics']['likeCount'],
KeyError: 'likeCount'
```

Code:
```py
data: List[Videos] = []

while all_urls:
    del all_urls[-50:]
    
    videos = Videos(videos_ids=all_urls[-50:], api_key=api_key)
    data.append(videos)

dataframes: List[DataFrame] = [v.to_df() for v in data]
print(dataframes)
```

**Comment by vmussa** [comment]
Hello @soukyomi it seems that YouTube Data API v3 doesn't provide some of the properties/statistics for some of the videos. I will add a `logging` warning if that is the case and catch this `KeyError` exception for all the metadata, which I should already be doing. As soon as I do it I will let you know. Thanks again for reporting this bug.

p.s.: The `Issues` section are now available in LABHDUFBA's repo.

**Comment by vmussa** [comment]
@soukyomi qualitube v0.1.2 is available through `pip install -U qualitube` with the above mentioned changes. Please let me know if the update fixes your problem! :)

**Comment by bitterteriyaki** [comment]
Hey, @vmussa. Thank you for the quick update.
I'm trying to use Qualitube code directly in my application but the noisy logs output messages that I wouldn't want to be shown. I believe that the library was not intended to be used that way, but rather with the `qualitube` terminal command, but it would be interesting if the library could be used both in the form of interactive commands and in the form of code. It would be nice if instead of `logging.warn` you use your own logger to control messages:
```py
logger = logging.getLogger('qualitube')
logger.warn(...)
```
This way, other users can manipulate the way in which the logs are displayed (show only errors? Maybe change the format of the log messages?). If you can accept this feature I would be very grateful. Thanks for the amazing work.

**Comment by vmussa** [comment]
Hey @soukyomi, I didn't think of this before, but the intent of this package is to be used both as a library or as a CLI app. In that sense, I'm accepting your suggestion and created a [PR with this change in LABHDUFBA's repo](https://github.com/LABHDUFBA/qualitube/pull/1), linked above this message also. It would be really nice if you could look at the PR and see if this is the way you are imagining and if it really enables the feature you requested. It would be great also if we continued the conversation at the PR's page. Thanks again!
